<?php
/**
 * Calculator seed data from Website details.xlsx.
 * Auto-generated.
 *
 * @package GTS
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

function gts_calculator_seed_fixed_tariffs_data() {
	return 	array(
		array(
			'country' => 'Germany',
			'city' => 'Hamburg',
			'route_type' => 'airport_city',
			'airport_keywords' => 'HAM',
			'price_standard' => 100.0,
			'price_e_class' => 170.0,
			'price_s_class' => 225.0,
			'price_v_class' => 180.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (HAM) - Hamburg city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Hamburg',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 100.0,
			'price_e_class' => 170.0,
			'price_s_class' => 225.0,
			'price_v_class' => 180.0,
			'night_surcharge_percent' => null,
			'notes' => 'Hamburg city - Hamburg city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Berlin',
			'route_type' => 'airport_city',
			'airport_keywords' => 'BER',
			'price_standard' => 90.0,
			'price_e_class' => 155.0,
			'price_s_class' => 190.0,
			'price_v_class' => 165.0,
			'night_surcharge_percent' => 10.0,
			'notes' => 'airport (BER) - Berlin city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Berlin',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 80.0,
			'price_e_class' => 135.0,
			'price_s_class' => 180.0,
			'price_v_class' => 145.0,
			'night_surcharge_percent' => null,
			'notes' => 'Berlin city - Berlin city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Essen',
			'route_type' => 'airport_city',
			'airport_keywords' => 'DUS',
			'price_standard' => 135.0,
			'price_e_class' => 155.0,
			'price_s_class' => 275.0,
			'price_v_class' => 180.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (DUS) - Essen city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Essen',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 125.0,
			'price_e_class' => 145.0,
			'price_s_class' => 255.0,
			'price_v_class' => 165.0,
			'night_surcharge_percent' => null,
			'notes' => 'Essen city - Essen city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Düsseldorf',
			'route_type' => 'airport_city',
			'airport_keywords' => 'DUS',
			'price_standard' => 90.0,
			'price_e_class' => 125.0,
			'price_s_class' => 180.0,
			'price_v_class' => 150.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (DUS) - Düsseldorf city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Düsseldorf',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 90.0,
			'price_e_class' => 125.0,
			'price_s_class' => 180.0,
			'price_v_class' => 150.0,
			'night_surcharge_percent' => null,
			'notes' => 'Düsseldorf city - Düsseldorf city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Frankfurt am Main',
			'route_type' => 'airport_city',
			'airport_keywords' => 'FRA',
			'price_standard' => 100.0,
			'price_e_class' => 125.0,
			'price_s_class' => 180.0,
			'price_v_class' => 135.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (FRA) - Frankfurt am Main city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Frankfurt am Main',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 100.0,
			'price_e_class' => 110.0,
			'price_s_class' => 155.0,
			'price_v_class' => 110.0,
			'night_surcharge_percent' => null,
			'notes' => 'Frankfurt am Main city - Frankfurt am Main city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Stuttgart',
			'route_type' => 'airport_city',
			'airport_keywords' => 'STR',
			'price_standard' => 125.0,
			'price_e_class' => 135.0,
			'price_s_class' => 180.0,
			'price_v_class' => 135.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (STR) - Stuttgart city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Stuttgart',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 110.0,
			'price_e_class' => 125.0,
			'price_s_class' => 155.0,
			'price_v_class' => 125.0,
			'night_surcharge_percent' => null,
			'notes' => 'Stuttgart city - Stuttgart city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Munich',
			'route_type' => 'airport_city',
			'airport_keywords' => 'MUC',
			'price_standard' => 110.0,
			'price_e_class' => 165.0,
			'price_s_class' => 190.0,
			'price_v_class' => 165.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (MUC) - Munich city',
			'enabled' => 1,
		),
		array(
			'country' => 'Germany',
			'city' => 'Munich',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 100.0,
			'price_e_class' => 165.0,
			'price_s_class' => 190.0,
			'price_v_class' => 155.0,
			'night_surcharge_percent' => null,
			'notes' => 'Munich city - Munich city',
			'enabled' => 1,
		),
		array(
			'country' => 'Switzerland',
			'city' => 'Geneva',
			'route_type' => 'airport_city',
			'airport_keywords' => 'GVA',
			'price_standard' => 125.0,
			'price_e_class' => 135.0,
			'price_s_class' => 175.0,
			'price_v_class' => 165.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (GVA) - Geneva city',
			'enabled' => 1,
		),
		array(
			'country' => 'Switzerland',
			'city' => 'Geneva',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 125.0,
			'price_e_class' => 135.0,
			'price_s_class' => 175.0,
			'price_v_class' => 165.0,
			'night_surcharge_percent' => null,
			'notes' => 'Geneva city - Geneva city',
			'enabled' => 1,
		),
		array(
			'country' => 'Switzerland',
			'city' => 'Zurich',
			'route_type' => 'airport_city',
			'airport_keywords' => 'ZRH',
			'price_standard' => 125.0,
			'price_e_class' => 155.0,
			'price_s_class' => 275.0,
			'price_v_class' => 190.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (ZRH) - Zurich city',
			'enabled' => 1,
		),
		array(
			'country' => 'Switzerland',
			'city' => 'Zurich',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 125.0,
			'price_e_class' => 155.0,
			'price_s_class' => 275.0,
			'price_v_class' => 190.0,
			'night_surcharge_percent' => null,
			'notes' => 'Zurich city - Zurich city',
			'enabled' => 1,
		),
		array(
			'country' => 'Austria',
			'city' => 'Vienna',
			'route_type' => 'airport_city',
			'airport_keywords' => 'VIE',
			'price_standard' => 80.0,
			'price_e_class' => 105.0,
			'price_s_class' => 155.0,
			'price_v_class' => 125.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (VIE) - Vienna city',
			'enabled' => 1,
		),
		array(
			'country' => 'Austria',
			'city' => 'Vienna',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 80.0,
			'price_e_class' => 105.0,
			'price_s_class' => 155.0,
			'price_v_class' => 80.0,
			'night_surcharge_percent' => null,
			'notes' => 'Vienna city - Vienna city',
			'enabled' => 1,
		),
		array(
			'country' => 'Austria',
			'city' => 'Vienna',
			'route_type' => 'airport_city',
			'airport_keywords' => '',
			'price_standard' => 200.0,
			'price_e_class' => 265.0,
			'price_s_class' => 400.0,
			'price_v_class' => 320.0,
			'night_surcharge_percent' => null,
			'notes' => 'Vienna City/Airport - Bratislava',
			'enabled' => 1,
		),
		array(
			'country' => 'France',
			'city' => 'Paris',
			'route_type' => 'airport_city',
			'airport_keywords' => 'CDG',
			'price_standard' => 100.0,
			'price_e_class' => 190.0,
			'price_s_class' => 300.0,
			'price_v_class' => 220.0,
			'night_surcharge_percent' => 20.0,
			'notes' => 'airport (CDG) - Paris city',
			'enabled' => 1,
		),
		array(
			'country' => 'France',
			'city' => 'Paris',
			'route_type' => 'airport_city',
			'airport_keywords' => 'ORY',
			'price_standard' => 100.0,
			'price_e_class' => 190.0,
			'price_s_class' => 300.0,
			'price_v_class' => 220.0,
			'night_surcharge_percent' => 20.0,
			'notes' => 'airport (ORY) - Paris city',
			'enabled' => 1,
		),
		array(
			'country' => 'France',
			'city' => 'Paris',
			'route_type' => 'airport_city',
			'airport_keywords' => 'BVA',
			'price_standard' => 165.0,
			'price_e_class' => 255.0,
			'price_s_class' => 495.0,
			'price_v_class' => 350.0,
			'night_surcharge_percent' => 20.0,
			'notes' => 'airport (BVA) - Paris city',
			'enabled' => 1,
		),
		array(
			'country' => 'France',
			'city' => 'Paris',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 80.0,
			'price_e_class' => 125.0,
			'price_s_class' => 210.0,
			'price_v_class' => 165.0,
			'night_surcharge_percent' => 20.0,
			'notes' => 'Paris city - Paris city',
			'enabled' => 1,
		),
		array(
			'country' => 'France',
			'city' => 'Transfers',
			'route_type' => 'airport_city',
			'airport_keywords' => '',
			'price_standard' => 70.0,
			'price_e_class' => 85.0,
			'price_s_class' => 125.0,
			'price_v_class' => 100.0,
			'night_surcharge_percent' => null,
			'notes' => 'Nice airport - Nice city',
			'enabled' => 1,
		),
		array(
			'country' => 'France',
			'city' => 'Transfers',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 70.0,
			'price_e_class' => 85.0,
			'price_s_class' => 125.0,
			'price_v_class' => 100.0,
			'night_surcharge_percent' => null,
			'notes' => 'Nice city - Nice city',
			'enabled' => 1,
		),
		array(
			'country' => 'Italy',
			'city' => 'Milan',
			'route_type' => 'airport_city',
			'airport_keywords' => 'MXP',
			'price_standard' => 145.0,
			'price_e_class' => 180.0,
			'price_s_class' => 330.0,
			'price_v_class' => 180.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (MXP) - Milan city',
			'enabled' => 1,
		),
		array(
			'country' => 'Italy',
			'city' => 'Milan',
			'route_type' => 'airport_city',
			'airport_keywords' => 'BGY',
			'price_standard' => 155.0,
			'price_e_class' => 180.0,
			'price_s_class' => 345.0,
			'price_v_class' => 205.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (BGY) - Milan city',
			'enabled' => 1,
		),
		array(
			'country' => 'Italy',
			'city' => 'Milan',
			'route_type' => 'airport_city',
			'airport_keywords' => 'LIN',
			'price_standard' => 95.0,
			'price_e_class' => 120.0,
			'price_s_class' => 235.0,
			'price_v_class' => 165.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (LIN) - Milan city',
			'enabled' => 1,
		),
		array(
			'country' => 'Italy',
			'city' => 'Milan',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 95.0,
			'price_e_class' => 120.0,
			'price_s_class' => 235.0,
			'price_v_class' => 165.0,
			'night_surcharge_percent' => null,
			'notes' => 'Milan city - Milan city',
			'enabled' => 1,
		),
		array(
			'country' => 'Italy',
			'city' => 'Rome',
			'route_type' => 'airport_city',
			'airport_keywords' => 'FCO',
			'price_standard' => 105.0,
			'price_e_class' => 110.0,
			'price_s_class' => 290.0,
			'price_v_class' => 155.0,
			'night_surcharge_percent' => 20.0,
			'notes' => 'airport (FCO) - Rome city',
			'enabled' => 1,
		),
		array(
			'country' => 'Italy',
			'city' => 'Rome',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 95.0,
			'price_e_class' => 105.0,
			'price_s_class' => 155.0,
			'price_v_class' => 125.0,
			'night_surcharge_percent' => 20.0,
			'notes' => 'Rome city - Rome city',
			'enabled' => 1,
		),
		array(
			'country' => 'Spain',
			'city' => 'Madrid',
			'route_type' => 'airport_city',
			'airport_keywords' => 'MAD',
			'price_standard' => 65.0,
			'price_e_class' => 100.0,
			'price_s_class' => 165.0,
			'price_v_class' => 135.0,
			'night_surcharge_percent' => 20.0,
			'notes' => 'airport (MAD) - Madrid city',
			'enabled' => 1,
		),
		array(
			'country' => 'Spain',
			'city' => 'Madrid',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 55.0,
			'price_e_class' => 90.0,
			'price_s_class' => 165.0,
			'price_v_class' => 125.0,
			'night_surcharge_percent' => 20.0,
			'notes' => 'Madrid city - Madrid city',
			'enabled' => 1,
		),
		array(
			'country' => 'Spain',
			'city' => 'Barcelona',
			'route_type' => 'airport_city',
			'airport_keywords' => 'BCN',
			'price_standard' => 90.0,
			'price_e_class' => 100.0,
			'price_s_class' => 165.0,
			'price_v_class' => 120.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (BCN) - Barcelona city',
			'enabled' => 1,
		),
		array(
			'country' => 'Spain',
			'city' => 'Barcelona',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 90.0,
			'price_e_class' => 100.0,
			'price_s_class' => 165.0,
			'price_v_class' => 120.0,
			'night_surcharge_percent' => null,
			'notes' => 'Barcelona city - Barcelona city',
			'enabled' => 1,
		),
		array(
			'country' => 'Portugal',
			'city' => 'Lisbon',
			'route_type' => 'airport_city',
			'airport_keywords' => 'LIS',
			'price_standard' => 70.0,
			'price_e_class' => 80.0,
			'price_s_class' => 140.0,
			'price_v_class' => 95.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (LIS) - Lisbon city',
			'enabled' => 1,
		),
		array(
			'country' => 'Portugal',
			'city' => 'Lisbon',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 70.0,
			'price_e_class' => 80.0,
			'price_s_class' => 140.0,
			'price_v_class' => 95.0,
			'night_surcharge_percent' => null,
			'notes' => 'Lisbon city - Lisbon city',
			'enabled' => 1,
		),
		array(
			'country' => 'Hungary',
			'city' => 'Budapest',
			'route_type' => 'airport_city',
			'airport_keywords' => 'BUD',
			'price_standard' => 65.0,
			'price_e_class' => 105.0,
			'price_s_class' => 180.0,
			'price_v_class' => 140.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (BUD) - Budapest city',
			'enabled' => 1,
		),
		array(
			'country' => 'Hungary',
			'city' => 'Budapest',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 50.0,
			'price_e_class' => 95.0,
			'price_s_class' => 180.0,
			'price_v_class' => 135.0,
			'night_surcharge_percent' => null,
			'notes' => 'Budapest city - Budapest city',
			'enabled' => 1,
		),
		array(
			'country' => 'Greece',
			'city' => 'Athens',
			'route_type' => 'airport_city',
			'airport_keywords' => 'ATH',
			'price_standard' => 90.0,
			'price_e_class' => 120.0,
			'price_s_class' => 195.0,
			'price_v_class' => 155.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (ATH) - Athens city',
			'enabled' => 1,
		),
		array(
			'country' => 'Greece',
			'city' => 'Athens',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 90.0,
			'price_e_class' => 120.0,
			'price_s_class' => 185.0,
			'price_v_class' => 150.0,
			'night_surcharge_percent' => null,
			'notes' => 'Athens city - Athens city',
			'enabled' => 1,
		),
		array(
			'country' => 'United Kingdom',
			'city' => 'London',
			'route_type' => 'airport_city',
			'airport_keywords' => 'LHR',
			'price_standard' => 205.0,
			'price_e_class' => 205.0,
			'price_s_class' => 310.0,
			'price_v_class' => 270.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (LHR) - London city',
			'enabled' => 1,
		),
		array(
			'country' => 'United Kingdom',
			'city' => 'London',
			'route_type' => 'airport_city',
			'airport_keywords' => 'LGW',
			'price_standard' => 250.0,
			'price_e_class' => 250.0,
			'price_s_class' => 385.0,
			'price_v_class' => 365.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (LGW) - London city',
			'enabled' => 1,
		),
		array(
			'country' => 'United Kingdom',
			'city' => 'London',
			'route_type' => 'airport_city',
			'airport_keywords' => 'LTN',
			'price_standard' => 250.0,
			'price_e_class' => 250.0,
			'price_s_class' => 385.0,
			'price_v_class' => 365.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (LTN) - London city',
			'enabled' => 1,
		),
		array(
			'country' => 'United Kingdom',
			'city' => 'London',
			'route_type' => 'airport_city',
			'airport_keywords' => 'STN',
			'price_standard' => 245.0,
			'price_e_class' => 275.0,
			'price_s_class' => 485.0,
			'price_v_class' => 330.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (STN) - London city',
			'enabled' => 1,
		),
		array(
			'country' => 'United Kingdom',
			'city' => 'London',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 205.0,
			'price_e_class' => 205.0,
			'price_s_class' => 295.0,
			'price_v_class' => 270.0,
			'night_surcharge_percent' => null,
			'notes' => 'London city - London city',
			'enabled' => 1,
		),
		array(
			'country' => 'Turkey',
			'city' => 'Istanbul',
			'route_type' => 'airport_city',
			'airport_keywords' => 'IST',
			'price_standard' => 145.0,
			'price_e_class' => 200.0,
			'price_s_class' => 495.0,
			'price_v_class' => 145.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (IST) - Istanbul city (european side)',
			'enabled' => 1,
		),
		array(
			'country' => 'Czech Republic',
			'city' => 'Prague',
			'route_type' => 'airport_city',
			'airport_keywords' => 'PRG',
			'price_standard' => 88.0,
			'price_e_class' => 90.0,
			'price_s_class' => 165.0,
			'price_v_class' => 135.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (PRG) - Prague city',
			'enabled' => 1,
		),
		array(
			'country' => 'Czech Republic',
			'city' => 'Prague',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 88.0,
			'price_e_class' => 90.0,
			'price_s_class' => 165.0,
			'price_v_class' => 135.0,
			'night_surcharge_percent' => null,
			'notes' => 'Prague city - Prague city',
			'enabled' => 1,
		),
		array(
			'country' => 'Belgium',
			'city' => 'Brussels',
			'route_type' => 'airport_city',
			'airport_keywords' => 'BRU',
			'price_standard' => 110.0,
			'price_e_class' => 110.0,
			'price_s_class' => 155.0,
			'price_v_class' => 110.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (BRU) - Brussels city',
			'enabled' => 1,
		),
		array(
			'country' => 'Denmark',
			'city' => 'Copenhagen',
			'route_type' => 'airport_city',
			'airport_keywords' => 'CPH',
			'price_standard' => 195.0,
			'price_e_class' => 200.0,
			'price_s_class' => 220.0,
			'price_v_class' => 205.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (CPH) - Copenhagen city',
			'enabled' => 1,
		),
		array(
			'country' => 'Denmark',
			'city' => 'Copenhagen',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 160.0,
			'price_e_class' => 165.0,
			'price_s_class' => 190.0,
			'price_v_class' => 180.0,
			'night_surcharge_percent' => null,
			'notes' => 'Copenhagen city - Copenhagen city',
			'enabled' => 1,
		),
		array(
			'country' => 'Netherlands',
			'city' => 'Amsterdam',
			'route_type' => 'airport_city',
			'airport_keywords' => 'AMS',
			'price_standard' => 135.0,
			'price_e_class' => 150.0,
			'price_s_class' => 185.0,
			'price_v_class' => 155.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (AMS) - Amsterdam city',
			'enabled' => 1,
		),
		array(
			'country' => 'Netherlands',
			'city' => 'Amsterdam',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 135.0,
			'price_e_class' => 150.0,
			'price_s_class' => 185.0,
			'price_v_class' => 155.0,
			'night_surcharge_percent' => null,
			'notes' => 'Amsterdam city - Amsterdam city',
			'enabled' => 1,
		),
		array(
			'country' => 'Serbia',
			'city' => 'Belgrade',
			'route_type' => 'airport_city',
			'airport_keywords' => 'BEG',
			'price_standard' => 75.0,
			'price_e_class' => 85.0,
			'price_s_class' => 200.0,
			'price_v_class' => 110.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (BEG) - Belgrade city',
			'enabled' => 1,
		),
		array(
			'country' => 'Serbia',
			'city' => 'Belgrade',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 70.0,
			'price_e_class' => 80.0,
			'price_s_class' => 190.0,
			'price_v_class' => 105.0,
			'night_surcharge_percent' => null,
			'notes' => 'Belgrade city - Belgrade city',
			'enabled' => 1,
		),
		array(
			'country' => 'Croatia',
			'city' => 'Zagreb',
			'route_type' => 'airport_city',
			'airport_keywords' => 'ZAIC',
			'price_standard' => 70.0,
			'price_e_class' => 90.0,
			'price_s_class' => 210.0,
			'price_v_class' => 135.0,
			'night_surcharge_percent' => null,
			'notes' => 'airport (ZAIC) - Zagreb city',
			'enabled' => 1,
		),
		array(
			'country' => 'Croatia',
			'city' => 'Zagreb',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 65.0,
			'price_e_class' => 85.0,
			'price_s_class' => 205.0,
			'price_v_class' => 130.0,
			'night_surcharge_percent' => null,
			'notes' => 'Zagreb city - Zagreb city',
			'enabled' => 1,
		),
		array(
			'country' => 'Romania',
			'city' => 'Bucharest',
			'route_type' => 'airport_city',
			'airport_keywords' => '',
			'price_standard' => 75.0,
			'price_e_class' => 90.0,
			'price_s_class' => 130.0,
			'price_v_class' => 120.0,
			'night_surcharge_percent' => null,
			'notes' => 'Bucharest airport - city',
			'enabled' => 1,
		),
		array(
			'country' => 'Romania',
			'city' => 'Bucharest',
			'route_type' => 'city_city',
			'airport_keywords' => '',
			'price_standard' => 75.0,
			'price_e_class' => 90.0,
			'price_s_class' => 130.0,
			'price_v_class' => 120.0,
			'night_surcharge_percent' => null,
			'notes' => 'Bucharest city - Bucharest city',
			'enabled' => 1,
		),
		array(
			'country' => 'Armenia',
			'city' => 'Yerevan',
			'route_type' => 'airport_city',
			'airport_keywords' => '',
			'price_standard' => 50.0,
			'price_e_class' => null,
			'price_s_class' => null,
			'price_v_class' => null,
			'night_surcharge_percent' => null,
			'notes' => 'Yerevan airport- Yerevan city',
			'enabled' => 1,
		),
	);
}

function gts_calculator_seed_night_rules_data() {
	return 	array(
		array(
			'region_key' => 'Europe',
			'night_from' => '22:00',
			'night_to' => '06:00',
			'charge_percent' => 25,
			'enabled' => 1,
		),
		array(
			'region_key' => 'The North America',
			'night_from' => '22:00',
			'night_to' => '06:00',
			'charge_percent' => 20,
			'enabled' => 1,
		),
		array(
			'region_key' => 'The Central America',
			'night_from' => '21:00',
			'night_to' => '06:00',
			'charge_percent' => 30,
			'enabled' => 1,
		),
		array(
			'region_key' => 'The South America',
			'night_from' => '21:00',
			'night_to' => '06:00',
			'charge_percent' => 30,
			'enabled' => 1,
		),
		array(
			'region_key' => 'Middle East',
			'night_from' => '22:00',
			'night_to' => '06:00',
			'charge_percent' => 0,
			'enabled' => 1,
		),
		array(
			'region_key' => 'Central Asia and the Far East',
			'night_from' => '22:00',
			'night_to' => '06:00',
			'charge_percent' => 30,
			'enabled' => 1,
		),
		array(
			'region_key' => 'Australia',
			'night_from' => '22:00',
			'night_to' => '06:00',
			'charge_percent' => 25,
			'enabled' => 1,
		),
		array(
			'region_key' => 'Afrika',
			'night_from' => '21:00',
			'night_to' => '06:00',
			'charge_percent' => 30,
			'enabled' => 1,
		),
	);
}

function gts_calculator_seed_country_region_map_data() {
	return 	array(
		array(
			'country' => 'Germany',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Switzerland',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Austria',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'France',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Italy',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Spain',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Portugal',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Hungary',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Greece',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'United Kingdom',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Czech Republic',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Belgium',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Netherlands',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Denmark',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Serbia',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Croatia',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Romania',
			'region_key' => 'Europe',
			'enabled' => 1,
		),
		array(
			'country' => 'Turkey',
			'region_key' => 'Middle East',
			'enabled' => 1,
		),
		array(
			'country' => 'Armenia',
			'region_key' => 'Central Asia and the Far East',
			'enabled' => 1,
		),
	);
}

function gts_calculator_seed_class_map_data() {
	return 	array(
		array(
			'class_key' => 'business',
			'price_column' => 'e_class',
			'enabled' => 1,
		),
		array(
			'class_key' => 'premium',
			'price_column' => 's_class',
			'enabled' => 1,
		),
		array(
			'class_key' => 'vip',
			'price_column' => 's_class',
			'enabled' => 1,
		),
		array(
			'class_key' => 'minivan',
			'price_column' => 'v_class',
			'enabled' => 1,
		),
		array(
			'class_key' => 'limousine',
			'price_column' => 's_class',
			'enabled' => 1,
		),
		array(
			'class_key' => 'special_request',
			'price_column' => 'standard',
			'enabled' => 1,
		),
	);
}

/**
 * One-time seed of calculator tariffs/rules from provided workbook data.
 */
function gts_calculator_seed_website_details_data_once() {
	if ( ! function_exists( 'update_field' ) ) {
		return;
	}

	$seed_version = '2026-03-03-v2';
	if ( get_option( 'gts_calculator_website_seed_version' ) === $seed_version ) {
		return;
	}

	update_field( 'calc_fixed_city_tariffs', gts_calculator_seed_fixed_tariffs_data(), 'option' );
	update_field( 'calc_night_rules_by_region', gts_calculator_seed_night_rules_data(), 'option' );
	update_field( 'calc_country_region_map', gts_calculator_seed_country_region_map_data(), 'option' );
	update_field( 'calc_fixed_class_column_map', gts_calculator_seed_class_map_data(), 'option' );

	update_option( 'gts_calculator_website_seed_version', $seed_version, false );
}
add_action( 'init', 'gts_calculator_seed_website_details_data_once' );
